### ISSUE TITLE
Exclude poles when performing periodic extension in symmetrizePattern()

### ISSUE THREAD

**Issue by martka** [EMS-TU-Ilmenau/EADF#12]
Since i'm not familiar with Python/NumPy syntax i might be mistaken but it appears to me that when the pattern is perdiocially extended in symmetrizePattern() the values at the poles ("north" and "south" pole of the sphere) are also "flipped" and "shifted". This should not be done.
In the EADF paper and Landmanns thesis it is always assumed that the sampled/measured data is sampled such that both poles are included (co-ele=0° and co-ele=180°). When doing the periodic extension they have to be excluded so that they don't appear twice in the periodic data. This is the reason why the number of co-elevation samples after periodification is not 2*N_theta but 2*(N_theta -1).

**Comment by SebastianSemper** [comment]
Seems like this is highly related to #9, so thanks for the clarification. :) I will fix it asap.
I was wondering whether the co-elevation dimension then always has an even or an odd number of samples? I think an odd number of DCT coeffcients would make the most sense, since then one has one DC component for every azimuth-angle.
