### ISSUE TITLE
Reconceptualization of the Wideband Case

### ISSUE THREAD

**Issue by SebastianSemper** [EMS-TU-Ilmenau/EADF#66]
It has come to my attention (read understanding) that the EADF we currently have is not really what one desires in practice if one considers the wideband case.

### Terminology of the Package

- *measurement/input data*: this data contains samples in CoElevation x Azimuth x Frequency x Polarization x Port. Here one hopes that these samples describe the behaviour of the antenna well enough to be considered accurate. This is usually the data we wish to feed into the constructor of the EADF object, along with some metadata.
- *narrowband*: this refers to the case, where we assume that the samples in frequency are not so widely spaced such that the behaviour of the antenna changes significantly over the specified frequencies
- *wideband*: this case is reflected in the fact that the frequency bins cover such a wide range that the antenna shows very different behaviour for different frequencies.
- *stationary subband*: this defines a region in frequency over which we can describe the antenna response reasonably well with one single set of CoEle x Azi x Pol x Port data values (not necessarily measurement data, it can be processed or calculated).
- *operating frequencies*: if used in an estimator, one usually has the scenario, where one or several antennas were deployed to take measurement as discrete frequencies occupying a certain band, thus using a certain bandwidth. these frequencies we the so called operating frequencies. generally, these are *independent* of the frequencies (still they have to be resided between the lowest and highest frequency present in the measurement data) used in the measurement data that describe the antenna as a system. for the estimator one needs the antenna response at the operating frequencies.
- *stationary operating subbands*:  during parameter estimation from measurement data speed and efficiency are critical. if the operating frequencies are in a stationary subband, we group these to a so called stationary operating subband. this saves precious computation time, since several frequencies can be treated with a single calculation.

### Purpose of the Package

It is now clear that we have *two* sets of frequencies. Those present in the measurement data and those needed during estimation, moreover the whole bandwith of the data is divided up in stationary subbands. The job of the package now is to use the measurement data in order to provide the division into stationary subbands (automatically or manually) and to provide the angle dependent antenna response at the operating frequencies while exploiting the previously derived stationarity along certain subbands.

### Structure of the Package

As such we need to make the following changes to the package. 
- Each EADF object also has to carry one or several sets of operating frequencies which are used during evaluation of the pattern. Since these normally do not change during the life time of the object they are considered static.
- We need something that represents the stationary subbands. At first this should be simply set manually, but we should have a code path in place, which allows easy (re)definition of the stationary subbands. Each stationary subband usually is defined by its lower and upper bounds in frequency and a set of CoEle-Freq x Azi-Freq x Pol x Port values representing the beampattern.
- We need a routine for smart and good interpolation of the measurement data along frequency to convert from the measured frequencies to the operating frequencies, since these two sets might contain different values. The only thing that should not be possible is extrapolation, since the russians still haven't invented the psychic glass sphere.
- The *Narrowband functions and their respective wideband-functions have to be refactored into a single function, which returns the antenna response for a given set of angles at the predefined operating frequencies while obeying the defined stationary subbands. 
- It now seems unnatural for these evaluation functions to produce Angle x Pol x Elem, since the slowest changing dimension should also be the slowest changing conceptually, so it should rather be Pol x Elem x Angle.

### Benefits

These conceptual changes change the structure of the package such that it more closely matches what beampatterns are used for and how they are viewed by the signal processing system as a whole.

@StellarSankalp, @MichaelDoebereiner, @ChristophWWagner what did I miss?

**Comment by MichaelDoebereiner** [comment]
I must say, I have a different interpretation of narrowband and wideband EADF.
In my opinion a narrowband EADF describes the antenna with only one frequency for a given band. If you have multiple bands, you have multiple narrowband EADFs, where each is treated separatly. So no interpolation along frequency. You use this EADF when the pattern doesn't change very much within the considered bandwidth.

The wideband  EADF describes the case, where you have multiple frequencies at a given band, where you can interpolate over frequency. This you need, when the pattern changes sufficiently along frequency.

There could be also a case, where you initiliaze a wideband EADF and want to obtain a narrowband EADF for a given bandwidth. That would represent the subband EADF idea.

So maybe we have to discuss this once more.

**Comment by SebastianSemper** [comment]
Okay, so my initial post tried to rephrase some terminology and introduce some new. So maybe I failed with that. For instance I would like to stress that I actually do not make a difference between wideband EADF and narrowband EADF, since the latter is only a special case of the former.

With all you comments you are right. Let me try to rephrase your first comment with the terms I introduced above:

*A "narrowband-EADF-case" is an EADF object, where only one stationary operating subband is present, which is described by a single CoEle x Azi x Pol x Port data structure. If you have multiple stationary operating subbands, you have one of these data structures for each subband. So no interpolation along frequency. You use this case, when the pattern doesn't change very much within the considered subbands, which makes them stationary subbands.*

In light of this, the other two paragraphs are hard to translate. I know what you mean and still you are right. I think we are both still confused by the others terminology.

**Comment by StellarSankalp** [comment]
Overall, this clarification of terminologies and usage of the package is quite helpful!
Building on the comments above, here is an edited/rephrased some of the terminologies.

Terminologies used in the package:

- measurement/input data: this data contains samples in CoElevation x Azimuth x Frequency x Polarization x Port. Here one hopes that these samples describe the behaviour of the antenna well enough to be considered accurate. This is usually the data we wish to feed into the constructor of the EADF object, along with some metadata.
 - measured frequencies: describes the frequency bins/samples/points along which antenna pattern (over CoElevation, Azimuth, Polarization, Port) is measured. Ideally, there would be a single measured frequency point for the narrowband case and multiple frequency points for the wideband case. 
- narrowband case: this refers to the case of a densely sampled frequency band, such that the behaviour of the antenna pattern minimally over the specified frequencies. One may also assume this to be a measurement only at the single center frequency of the considered narrowband over which a single EADF can be defined. 
- wideband case: this case is reflected in the fact that the frequency bins cover such a wide range that the antenna shows very different behaviour for different frequencies. Hence, one would typically assume that the wideband contains several center frequencies over which a unique EADF can be derived. 
 - operating frequencies: when utilizing the EADF to perform parameter estimation (e.g. DoA), one usually considers the estimation for a certain frequency bin. The set of frequency bins over which estimation is performed is termed operating frequencies. For a given scenario, the operating frequencies may be independent of the measured frequencies, yet lie in the defined bandwidth of the antenna. Antenna pattern for operating frequencies that are not present by the set of measured frequencies can be obtained through interpolation along frequency using the EADF package. Interpolation over frequency indeed assumes that the measured frequency set obeys the sampling theorem.

> if used in an estimator, one usually has the scenario, where one or several antennas were deployed to take the measurement at discrete frequencies occupying a certain band, thus using a certain bandwidth. these frequencies we the so-called operating frequencies.
`not entirely sure if I understand this part from the previous description`

- stationary subband: this defines a region within frequency bandwidth over which we can describe the antenna response reasonably well with one single set of CoEle x Azi x Pol x Port data values (not necessarily measurement data, it can be processed or calculated). For the narrowband case, the complete measured bandwidth is itself the stationary subband. In other words, the notion of stationary subbands seeks to define multiple narrowband-sets within a wideband.
`The idea to derive a single set of CoEle x Azi x Pol x Port data essentially refers to the delay-domain pattern selection, right?`
- stationary operating subband: during parameter estimation from measurement data, speed and efficiency are critical. If the operating frequencies lie within a stationary subband, we group these to a so called stationary operating subband. this saves precious computation time, since several frequencies can be treated with a single calculation. Thus, the definition of the EADF is based on the measured antenna pattern within this stationary subband and estimation for any of the frequency bins within it is performed using this EADF.

Purpose of the Package

It is now clear that we have two sets of frequencies. Those present in the measurement data and those needed during estimation. Moreover, the whole bandwith of the data is divided up in stationary subbands. The job of the package now is to use the measurement data in order to provide the division into stationary subbands (automatically or manually) and to provide the angle dependent antenna response at the operating frequencies while exploiting the previously derived stationarity along certain subbands.
`precise!`

**Comment by SebastianSemper** [comment]
Done.
